apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: online-boutique-dashboard
    files:
      - online-boutique.json=grafana/online-boutique.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"

    resources:
      - grafana/online-boutique-dashboard.yaml
      - alerts/online-boutique-alerts.yaml
