apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/adservice
    newName: ghcr.io/prithvi-a24/online-boutique-adservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/cartservice
    newName: ghcr.io/prithvi-a24/online-boutique-cartservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/checkoutservice
    newName: ghcr.io/prithvi-a24/online-boutique-checkoutservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/currencyservice
    newName: ghcr.io/prithvi-a24/online-boutique-currencyservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/emailservice
    newName: ghcr.io/prithvi-a24/online-boutique-emailservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/frontend
    newName: ghcr.io/prithvi-a24/online-boutique-frontend
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/loadgenerator
    newName: ghcr.io/prithvi-a24/online-boutique-loadgenerator
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/paymentservice
    newName: ghcr.io/prithvi-a24/online-boutique-paymentservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/productcatalogservice
    newName: ghcr.io/prithvi-a24/online-boutique-productcatalogservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/recommendationservice
    newName: ghcr.io/prithvi-a24/online-boutique-recommendationservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df

  - name: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/shippingservice
    newName: ghcr.io/prithvi-a24/online-boutique-shippingservice
    newTag: 8681b0d51844c1f8a92385a774a9b120478e82df